var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:40000/";

MongoClient.connect(url, {useNewUrlParser: true, useUnifiedTopology: true},function(err, db) {
  if (err) throw err;
  var dbo = db.db("AllInformation");
  console.log("Switched to "+dbo.databaseName+" database");
  var allsubject = [{ SubjectID: "240-101", NameSubject: "INTRODUCTION TO COMPUTER PROGRAMMING",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [1,2,3,4]} },
                    { SubjectID: "240-201", NameSubject: "COMPUTER ENGINEERING SOFTWARE LABORATORY I",
                      credit: 1, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-202", NameSubject: "COMPUTER ENGINEERING HARDWARE LABORATORY I",
                      credit: 1, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-205", NameSubject: "ELECTRIC CIRCUITS",
                      credit: 1, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-206", NameSubject: "INTRODUCTION TO COMPUTER NETWORKS",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:65,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-207", NameSubject: "PROGRAMMING AND DATA STRUCTURES",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-208", NameSubject: "DIGITAL LOGIC AND DESIGN",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-215", NameSubject: "COMPUTER ENGINEERING MATHEMATICS",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-203", NameSubject: "COMPUTER ENGINEERING SOFTWARE LABORATORY II",
                      credit: 1, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-204", NameSubject: "COMPUTER ENGINEERING HARDWARE LABORATORY II",
                      credit: 1, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} }, 
                    { SubjectID: "240-209", NameSubject: "BASIC ELECTRONICS",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-210", NameSubject: "PROGRAMING TECHNIQUES",
                      credit: 2, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-211", NameSubject: "SOFTWARE ENGINEERING",
                      credit: 2, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-212", NameSubject: "PROBABILITY AND STATISTICS",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-213", NameSubject: "DISCRETE MATHEMATICS",
                      credit: 2, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-214", NameSubject: "DATA COMMUNICATIONS AND NETWORKING",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:40,
                      propertiesStudent:{ grade: [2,3,4]} },
                    { SubjectID: "240-301", NameSubject: "ADVANCED COMPUTER ENGINEERING LABORATORY I",
                      credit: 1, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:30,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-303", NameSubject: "ETHICAL, LEGAL AND SOCIAL ISSUES IN COMPUTER PROFESSION",
                      credit: 1, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-304", NameSubject: "COMPUTER OPERATING SYSTEMS",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:99,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-305", NameSubject: "DATABASE SYSTEMS",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:60,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-306", NameSubject: "WIRELESS AND MOBILE NETWORKS",
                      credit: 2, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:60,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-307", NameSubject: "COMPUTER ARCHITECTURE AND ORGANIZATION",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-360", NameSubject: "NETWORK MODELING AND PERFORMANCE ANALYSIS",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:30,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-302", NameSubject: "ADVANCED COMPUTER ENGINEERING LABORATORY II",
                      credit: 1, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:30,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-308", NameSubject: "COMPUTER ENGINEERING PROJECT PREPAREATION",
                      credit: 2, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:99,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-309", NameSubject: "MICROCONTROLLER AND INTERFACING",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:50,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-310", NameSubject: "ALGORITHMS : DESIGN AND ANALYSIS",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:30,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-311", NameSubject: "DISTRIBUTED COMPUTING AND WEB TECHNOLOGIES",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:35,
                      propertiesStudent:{ grade: [3,4]} }, 
                    { SubjectID: "240-312", NameSubject: "COMPUTER SECURITY",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:99,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-361", NameSubject: "NETWORK PROTOCOLS",
                      credit: 3, status : "close", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:65,
                      propertiesStudent:{ grade: [3,4]} },
                    { SubjectID: "240-460", NameSubject: "INTERNET PROGRAMMING",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:65,
                      propertiesStudent:{ grade: [4]} }, 
                    { SubjectID: "240-438", NameSubject: "SPECIAL TOPIC IN INFORMATION ENGINEERING I (MODERN MOBILE APPLICATION DEVELOPMENT)",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:30,
                      propertiesStudent:{ grade: [3,4]} },    
                    { SubjectID: "240-401", NameSubject: "COMPUTER ENGINEERING PROJECT I",
                      credit: 3, status : "open", NumberofStudentRegistered:0, MaximumNumberofStudentRegistered:99,
                      propertiesStudent:{ grade: [4]} }, 
                   ];
  dbo.collection("Subject information").insertMany(allsubject, function(err, res) {
    if (err) throw err;
    console.log(res.insertedCount+ " document inserted");
    db.close();
  });
  // dbo.collection("Subject information").insertMany(allsubject, function(err, res) {
  //   if (err) throw err;
  //   console.log(res.insertedCount+" document inserted");
  //   db.close();
  // });
});